2018-03-18 18:44:43,779 ERROR: Exception on /archive/24/ [GET] [in /Users/nielsenz/flaskNotes/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/flask/app.py", line 1740, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/werkzeug/wrappers.py", line 921, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/werkzeug/wrappers.py", line 59, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/werkzeug/test.py", line 923, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'bool' object is not callable
2018-03-18 18:45:34,546 INFO: Microblog startup [in /Users/nielsenz/flaskNotes/app/__init__.py:51]
2018-03-18 18:49:30,827 INFO: Microblog startup [in /Users/nielsenz/flaskNotes/app/__init__.py:51]
2018-03-18 18:49:42,113 ERROR: Exception on /archive/24/ [GET] [in /Users/nielsenz/flaskNotes/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/flask/app.py", line 1740, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/werkzeug/wrappers.py", line 921, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/werkzeug/wrappers.py", line 59, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/werkzeug/test.py", line 923, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'bool' object is not callable
2018-03-18 18:51:49,016 INFO: Microblog startup [in /Users/nielsenz/flaskNotes/app/__init__.py:51]
2018-03-18 18:51:51,826 ERROR: Exception on /archive/25/ [GET] [in /Users/nielsenz/flaskNotes/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/flask/app.py", line 1740, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/werkzeug/wrappers.py", line 921, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/werkzeug/wrappers.py", line 59, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/werkzeug/test.py", line 923, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'bool' object is not callable
2018-03-18 18:52:44,662 INFO: Microblog startup [in /Users/nielsenz/flaskNotes/app/__init__.py:51]
2018-03-18 18:52:50,736 ERROR: Exception on /archive/26/ [GET] [in /Users/nielsenz/flaskNotes/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/flask/app.py", line 1740, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/werkzeug/wrappers.py", line 921, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/werkzeug/wrappers.py", line 59, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/werkzeug/test.py", line 923, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'bool' object is not callable
2018-03-18 18:53:07,321 INFO: Microblog startup [in /Users/nielsenz/flaskNotes/app/__init__.py:51]
2018-03-18 18:53:23,985 INFO: Microblog startup [in /Users/nielsenz/flaskNotes/app/__init__.py:51]
2018-03-18 18:53:29,000 ERROR: Exception on /archive/25/ [GET] [in /Users/nielsenz/flaskNotes/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/flask/app.py", line 1740, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/werkzeug/wrappers.py", line 921, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/werkzeug/wrappers.py", line 59, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/werkzeug/test.py", line 923, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'bool' object is not callable
2018-03-18 18:53:56,600 INFO: Microblog startup [in /Users/nielsenz/flaskNotes/app/__init__.py:51]
2018-03-18 19:00:03,636 INFO: Microblog startup [in /Users/nielsenz/flaskNotes/app/__init__.py:51]
2018-03-18 19:00:13,705 ERROR: Exception on /archive/27/ [GET] [in /Users/nielsenz/flaskNotes/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/flask/app.py", line 1740, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/werkzeug/wrappers.py", line 921, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/werkzeug/wrappers.py", line 59, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/Users/nielsenz/flaskNotes/lib/python3.6/site-packages/werkzeug/test.py", line 923, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'bool' object is not callable
2018-03-18 19:03:34,756 INFO: Microblog startup [in /Users/nielsenz/flaskNotes/app/__init__.py:51]
